import { useRouter } from "expo-router";
import { useMemo, useState } from "react";
import { Alert, FlatList, KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { AppIcon } from "@/components/app-icon"; import { AppScreen } from "@/components/app-screen"; import { AudiencePicker } from "@/components/audience-picker"; import { MemberAvatar } from "@/components/member-avatar"; import { useAppTheme } from "@/hooks/use-app-theme"; import { haptic } from "@/lib/haptics"; import { useHappy } from "@/lib/happy-store";

const prompts = ["I’m proud of you for…", "Your joy reminded me…", "I hope you remember…"];
export default function EncouragementComposeScreen() {
  const router = useRouter(); const { colors } = useAppTheme(); const { state, sendEncouragement } = useHappy(); const members = useMemo(() => state.members.filter((member) => member.id !== state.currentMemberId), [state.members, state.currentMemberId]); const [memberId, setMemberId] = useState(members[0]?.id ?? ""); const [podId, setPodId] = useState<string | undefined>(); const [message, setMessage] = useState(""); const [sending, setSending] = useState(false);
  async function send() { if (!memberId || !message.trim() || sending) return; setSending(true); try { await sendEncouragement({ toMemberId: memberId, message, podId }); haptic.success(); router.back(); } catch { Alert.alert("Kindness not sent", "HappyMe couldn’t reach the cloud. Your note is still here so you can try again."); } finally { setSending(false); } }
  return <AppScreen edges={["top", "bottom", "left", "right"]}><KeyboardAvoidingView behavior={Platform.OS === "ios" ? "padding" : undefined} style={styles.flex}><ScrollView keyboardDismissMode={Platform.OS === "ios" ? "interactive" : "on-drag"} keyboardShouldPersistTaps="handled" showsVerticalScrollIndicator={false} contentContainerStyle={styles.container}><View style={styles.topBar}><Pressable accessibilityRole="button" accessibilityLabel="Close" onPress={() => router.back()} style={[styles.close, { backgroundColor: colors.surfaceAlt }]}><AppIcon name="close" size={21} color={colors.ink} /></Pressable><Text style={[styles.topTitle, { color: colors.ink }]}>Send kindness</Text><View style={styles.spacer} /></View><View><Text style={[styles.title, { color: colors.ink }]}>Who needs a little light?</Text><Text style={[styles.subtitle, { color: colors.muted }]}>No counters. No public score. Just a note between people.</Text></View><FlatList horizontal data={members} keyExtractor={(item) => item.id} showsHorizontalScrollIndicator={false} contentContainerStyle={styles.people} renderItem={({ item }) => { const selected = item.id === memberId; return <Pressable onPress={() => { setMemberId(item.id); setPodId(undefined); haptic.selection(); }} style={[styles.personChoice, { backgroundColor: selected ? colors.primarySoft : colors.surface, borderColor: selected ? colors.primary : colors.border }]}><MemberAvatar member={item} size={42} /><Text style={[styles.personName, { color: colors.ink }]}>{item.name}</Text></Pressable>; }} /><View style={styles.promptRow}>{prompts.map((prompt) => <Pressable key={prompt} onPress={() => setMessage(prompt)} style={[styles.promptChip, { backgroundColor: colors.surfaceAlt }]}><Text style={[styles.promptText, { color: colors.muted }]}>{prompt}</Text></Pressable>)}</View><TextInput multiline value={message} onChangeText={setMessage} maxLength={360} placeholder="Write something true and generous…" placeholderTextColor={colors.muted} style={[styles.input, { color: colors.ink, backgroundColor: colors.surface, borderColor: colors.border }]} /><View><Text style={[styles.audienceLabel, { color: colors.muted }]}>OPTIONAL POD CONTEXT</Text><AudiencePicker pods={state.pods} currentMemberId={state.currentMemberId} selectedPodId={podId} onChange={setPodId} privateLabel="Direct note" memberId={memberId} compact /></View><Pressable accessibilityRole="button" accessibilityLabel="Send encouragement" disabled={!message.trim() || !memberId} onPress={send} style={({ pressed }) => [styles.send, { backgroundColor: message.trim() && memberId ? colors.coral : colors.border, opacity: pressed ? 0.76 : 1 }]}><Text style={styles.sendText}>Send encouragement</Text><AppIcon name="heart" size={19} color="#FFFFFF" /></Pressable></ScrollView></KeyboardAvoidingView></AppScreen>;
}
const styles = StyleSheet.create({ flex: { flex: 1 }, container: { flexGrow: 1, paddingHorizontal: 18, paddingTop: 8, paddingBottom: 30, gap: 19 }, topBar: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, close: { width: 42, height: 42, borderRadius: 21, alignItems: "center", justifyContent: "center" }, topTitle: { fontSize: 15, lineHeight: 20, fontWeight: "800" }, spacer: { width: 42 }, title: { fontSize: 28, lineHeight: 35, fontWeight: "800", letterSpacing: -0.6 }, subtitle: { fontSize: 14, lineHeight: 20, marginTop: 4, maxWidth: 330 }, people: { gap: 9, paddingRight: 18 }, personChoice: { minWidth: 94, minHeight: 82, borderRadius: 21, borderWidth: 1, alignItems: "center", justifyContent: "center", gap: 5 }, personName: { fontSize: 12, lineHeight: 16, fontWeight: "800" }, promptRow: { flexDirection: "row", flexWrap: "wrap", gap: 7 }, promptChip: { minHeight: 35, paddingHorizontal: 11, borderRadius: 18, justifyContent: "center" }, promptText: { fontSize: 11, lineHeight: 15, fontWeight: "700" }, input: { minHeight: 150, borderRadius: 22, borderWidth: 1, padding: 15, textAlignVertical: "top", fontSize: 16, lineHeight: 24 }, audienceLabel: { fontSize: 10, lineHeight: 14, letterSpacing: 1.1, fontWeight: "800", marginBottom: 8 }, send: { minHeight: 54, borderRadius: 27, marginTop: 2, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8 }, sendText: { color: "#FFFFFF", fontSize: 15, lineHeight: 20, fontWeight: "900" } });
