import { useLocalSearchParams, useRouter } from "expo-router";
import { FlatList, Pressable, StyleSheet, Text, View } from "react-native";
import { AppIcon } from "@/components/app-icon"; import { AppScreen } from "@/components/app-screen"; import { EmptyState } from "@/components/empty-state"; import { MemberAvatar } from "@/components/member-avatar"; import { MomentCard } from "@/components/moment-card"; import { useAppTheme } from "@/hooks/use-app-theme"; import { useHappy } from "@/lib/happy-store";
export default function PodDetailScreen() {
  const { id } = useLocalSearchParams<{ id: string }>(); const router = useRouter(); const { colors } = useAppTheme(); const { state } = useHappy(); const pod = state.pods.find((item) => item.id === id); const moments = state.moments.filter((moment) => moment.podId === id).sort((a, b) => b.createdAt.localeCompare(a.createdAt));
  if (!pod) return <AppScreen><View style={styles.missing}><Text style={[styles.missingTitle, { color: colors.ink }]}>This pod is not available.</Text><Pressable onPress={() => router.back()}><Text style={[styles.backLink, { color: colors.coral }]}>Go back</Text></Pressable></View></AppScreen>;
  const members = pod.memberIds.map((memberId) => state.members.find((member) => member.id === memberId)).filter(Boolean);
  const header = <View style={styles.header}><View style={styles.topBar}><Pressable onPress={() => router.back()} style={({ pressed }) => [styles.circle, { backgroundColor: colors.surface, borderColor: colors.border, opacity: pressed ? 0.6 : 1 }]}><AppIcon name="chevron-back" size={21} color={colors.ink} /></Pressable><Text style={[styles.topTitle, { color: colors.ink }]}>Private pod</Text><View style={styles.spacer} /></View><View style={[styles.identity, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={[styles.podMark, { backgroundColor: pod.color }]}><AppIcon name="people" size={28} color="#FFFFFF" /></View><Text style={[styles.title, { color: colors.ink }]}>{pod.name}</Text><Text style={[styles.description, { color: colors.muted }]}>{pod.description}</Text><View style={styles.members}>{members.map((member) => member ? <MemberAvatar key={member.id} member={member} size={38} /> : null)}</View><View style={[styles.invite, { backgroundColor: colors.surfaceAlt }]}><View><Text style={[styles.inviteLabel, { color: colors.muted }]}>INVITATION CODE</Text><Text style={[styles.inviteCode, { color: colors.ink }]}>{pod.inviteCode}</Text></View><AppIcon name="key-outline" size={21} color={colors.coral} /></View></View><Pressable onPress={() => router.push({ pathname: "/compose", params: { podId: pod.id } } as never)} style={({ pressed }) => [styles.add, { backgroundColor: colors.ink, opacity: pressed ? 0.75 : 1 }]}><AppIcon name="add" size={20} color={colors.background} /><Text style={[styles.addText, { color: colors.background }]}>Add a moment here</Text></Pressable><View><Text style={[styles.feedTitle, { color: colors.ink }]}>Shared light</Text><Text style={[styles.feedSubtitle, { color: colors.muted }]}>{moments.length} moments in this circle</Text></View></View>;
  return <AppScreen edges={["top", "left", "right"]}><FlatList data={moments} keyExtractor={(item) => item.id} contentContainerStyle={styles.list} ListHeaderComponent={header} ListEmptyComponent={<EmptyState icon="sparkles-outline" title="This pod is ready" body="Share the first bright spot with your circle." />} ItemSeparatorComponent={() => <View style={styles.separator} />} renderItem={({ item }) => <MomentCard moment={item} authorName={state.members.find((member) => member.id === item.authorId)?.name ?? "Someone"} podName={pod.name} />} showsVerticalScrollIndicator={false} /></AppScreen>;
}
const styles = StyleSheet.create({ list: { paddingHorizontal: 18, paddingBottom: 34 }, header: { paddingTop: 8, paddingBottom: 16, gap: 18 }, topBar: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, circle: { width: 44, height: 44, borderRadius: 22, borderWidth: 1, alignItems: "center", justifyContent: "center" }, topTitle: { fontSize: 14, lineHeight: 19, fontWeight: "800" }, spacer: { width: 44 }, identity: { borderRadius: 28, borderWidth: 1, padding: 21, alignItems: "center" }, podMark: { width: 62, height: 62, borderRadius: 21, alignItems: "center", justifyContent: "center" }, title: { fontSize: 27, lineHeight: 34, fontWeight: "800", marginTop: 14 }, description: { fontSize: 14, lineHeight: 21, textAlign: "center", marginTop: 5, maxWidth: 300 }, members: { flexDirection: "row", marginTop: 16 }, invite: { width: "100%", borderRadius: 18, paddingHorizontal: 15, paddingVertical: 12, marginTop: 18, flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, inviteLabel: { fontSize: 10, lineHeight: 14, letterSpacing: 1.1, fontWeight: "800" }, inviteCode: { fontSize: 17, lineHeight: 22, letterSpacing: 2, fontWeight: "900", marginTop: 2 }, add: { minHeight: 50, borderRadius: 25, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8 }, addText: { fontSize: 14, lineHeight: 19, fontWeight: "900" }, feedTitle: { fontSize: 22, lineHeight: 28, fontWeight: "800" }, feedSubtitle: { fontSize: 13, lineHeight: 18, marginTop: 2 }, separator: { height: 13 }, missing: { flex: 1, alignItems: "center", justifyContent: "center", gap: 12, padding: 24 }, missingTitle: { fontSize: 21, lineHeight: 28, fontWeight: "800" }, backLink: { fontSize: 14, lineHeight: 19, fontWeight: "800" } });
