import { useLocalSearchParams, useRouter } from "expo-router";
import { useEffect, useState } from "react";
import { ActivityIndicator, KeyboardAvoidingView, Platform, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { AppIcon } from "@/components/app-icon";
import { AppScreen } from "@/components/app-screen";
import { useAppTheme } from "@/hooks/use-app-theme";
import { validatePassword } from "@/lib/auth-validation";
import { useAuth } from "@/lib/auth";
import { haptic } from "@/lib/haptics";
import { supabase } from "@/lib/supabase";

export default function ResetPasswordScreen() {
  const { code } = useLocalSearchParams<{ code?: string }>(); const router = useRouter(); const { colors } = useAppTheme(); const { updatePassword } = useAuth(); const [password, setPassword] = useState(""); const [confirm, setConfirm] = useState(""); const [busy, setBusy] = useState(Boolean(code)); const [error, setError] = useState(""); const valid = !busy && !validatePassword(password) && password === confirm;
  useEffect(() => { if (!code) return; supabase.auth.exchangeCodeForSession(code).then(({ error: exchangeError }) => { if (exchangeError) setError("That reset link is invalid or expired. Request a new one from sign in."); setBusy(false); }); }, [code]);
  async function save() { if (!valid || busy) return; setBusy(true); setError(""); try { await updatePassword(password); haptic.success(); router.replace("/" as never); } catch (cause) { setError(cause instanceof Error ? cause.message : "Your password could not be updated."); haptic.error(); } finally { setBusy(false); } }
  return <AppScreen edges={["top", "bottom", "left", "right"]}><KeyboardAvoidingView behavior={Platform.OS === "ios" ? "padding" : undefined} style={styles.content}><View style={[styles.icon, { backgroundColor: colors.primarySoft }]}><AppIcon name="key" size={32} color={colors.coral} /></View><Text style={[styles.title, { color: colors.ink }]}>Choose a new password</Text><Text style={[styles.body, { color: colors.muted }]}>Use at least 8 characters. Your other HappyMe sessions will use the new password the next time they sign in.</Text><TextInput secureTextEntry value={password} onChangeText={setPassword} placeholder="New password" placeholderTextColor={colors.muted} style={[styles.input, { backgroundColor: colors.surface, borderColor: colors.border, color: colors.ink }]} /><TextInput secureTextEntry value={confirm} onChangeText={setConfirm} placeholder="Confirm new password" placeholderTextColor={colors.muted} style={[styles.input, { backgroundColor: colors.surface, borderColor: confirm && confirm !== password ? colors.danger : colors.border, color: colors.ink }]} />{error ? <Text accessibilityRole="alert" style={[styles.error, { color: colors.danger }]}>{error}</Text> : null}<Pressable disabled={!valid || busy} onPress={save} style={[styles.button, { backgroundColor: valid ? colors.primary : colors.border }]}>{busy ? <ActivityIndicator color={colors.ink} /> : <Text style={[styles.buttonText, { color: colors.ink }]}>Update password</Text>}</Pressable></KeyboardAvoidingView></AppScreen>;
}
const styles = StyleSheet.create({ content: { flex: 1, justifyContent: "center", paddingHorizontal: 24, gap: 13 }, icon: { width: 68, height: 68, borderRadius: 24, alignSelf: "center", alignItems: "center", justifyContent: "center" }, title: { fontSize: 28, lineHeight: 35, fontWeight: "900", textAlign: "center" }, body: { fontSize: 15, lineHeight: 21, textAlign: "center", marginBottom: 8 }, input: { minHeight: 53, borderRadius: 17, borderWidth: 1, paddingHorizontal: 15, fontSize: 15, lineHeight: 21 }, error: { fontSize: 15, lineHeight: 21, textAlign: "center", fontWeight: "700" }, button: { minHeight: 56, paddingVertical: 12, borderRadius: 27, alignItems: "center", justifyContent: "center", marginTop: 4 }, buttonText: { fontSize: 15, lineHeight: 20, fontWeight: "900" } });
