import { useLocalSearchParams, useRouter } from "expo-router";
import { useState } from "react";
import { ActivityIndicator, Alert, FlatList, KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { AppIcon } from "@/components/app-icon"; import { AppScreen } from "@/components/app-screen"; import { AudiencePicker } from "@/components/audience-picker"; import { JoyBloom } from "@/components/joy-bloom"; import { MoodChip } from "@/components/mood-chip"; import { TagSuggestions } from "@/components/tag-suggestions"; import { useAppTheme } from "@/hooks/use-app-theme"; import type { Mood } from "@/lib/domain"; import { useHappy } from "@/lib/happy-store";
const moods: Mood[] = ["sunny", "peaceful", "proud", "connected"];
export default function ComposeScreen() {
  const router = useRouter(); const params = useLocalSearchParams<{ podId?: string }>(); const { colors } = useAppTheme(); const { state, addMoment } = useHappy(); const [text, setText] = useState(""); const [mood, setMood] = useState<Mood>("sunny"); const [podId, setPodId] = useState<string | undefined>(params.podId); const [tags, setTags] = useState<string[]>([]); const [celebrating, setCelebrating] = useState(false); const [saving, setSaving] = useState(false);
  async function save() { if (!text.trim() || celebrating || saving) return; setSaving(true); try { await addMoment({ text, mood, podId, tags }); setCelebrating(true); } catch { Alert.alert("Moment not saved", "HappyMe couldn’t reach the cloud. Your draft is still here so you can try again."); } finally { setSaving(false); } }
  return <><AppScreen edges={["top", "bottom", "left", "right"]}><KeyboardAvoidingView behavior={Platform.OS === "ios" ? "padding" : undefined} style={styles.flex}><ScrollView keyboardDismissMode={Platform.OS === "ios" ? "interactive" : "on-drag"} keyboardShouldPersistTaps="handled" showsVerticalScrollIndicator={false} contentContainerStyle={styles.container}><View style={styles.topBar}><Pressable accessibilityRole="button" accessibilityLabel="Close" onPress={() => router.back()} style={({ pressed }) => [styles.close, { backgroundColor: colors.surfaceAlt, opacity: pressed ? 0.6 : 1 }]}><AppIcon name="close" size={21} color={colors.ink} /></Pressable><Text style={[styles.modalTitle, { color: colors.ink }]}>Keep this moment</Text><View style={styles.topSpacer} /></View>
    <View style={[styles.editor, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text style={[styles.prompt, { color: colors.ink }]}>What felt good?</Text><Text style={[styles.helper, { color: colors.muted }]}>Write it like a note to your future self.</Text><TextInput autoFocus multiline value={text} onChangeText={setText} maxLength={800} placeholder="Today, I want to remember…" placeholderTextColor={colors.muted} style={[styles.input, { color: colors.ink, borderColor: colors.border, backgroundColor: colors.background }]} /><Text style={[styles.counter, { color: colors.muted }]}>{text.length}/800</Text></View>
    <View><Text style={[styles.sectionLabel, { color: colors.ink }]}>How did it feel?</Text><FlatList horizontal data={moods} keyExtractor={(item) => item} showsHorizontalScrollIndicator={false} contentContainerStyle={styles.horizontal} renderItem={({ item }) => <MoodChip mood={item} selected={mood === item} onPress={() => setMood(item)} />} /></View>
    <View><Text style={[styles.sectionLabel, { color: colors.ink }]}>Add a little thread</Text><Text style={[styles.sectionHelper, { color: colors.muted }]}>Optional tags make favorite kinds of joy easier to find later.</Text><TagSuggestions text={text} mood={mood} selectedTags={tags} onChange={setTags} allowCustom /></View>
    <View><Text style={[styles.sectionLabel, { color: colors.ink }]}>Who can see it?</Text><AudiencePicker pods={state.pods} currentMemberId={state.currentMemberId} selectedPodId={podId} onChange={setPodId} /></View>
    <Pressable accessibilityRole="button" accessibilityState={{ disabled: !text.trim() || celebrating || saving }} disabled={!text.trim() || celebrating || saving} onPress={save} style={({ pressed }) => [styles.save, { backgroundColor: text.trim() ? colors.primary : colors.border, opacity: pressed ? 0.76 : 1 }]}>{saving ? <ActivityIndicator color={colors.ink} /> : <><Text style={[styles.saveText, { color: colors.ink }]}>{celebrating ? "Growing your garden…" : "Save moment"}</Text><AppIcon name="sparkles" size={19} color={colors.ink} /></>}</Pressable>
  </ScrollView></KeyboardAvoidingView></AppScreen><JoyBloom visible={celebrating} onComplete={() => router.back()} /></>;
}
const styles = StyleSheet.create({ flex: { flex: 1 }, container: { flexGrow: 1, paddingHorizontal: 18, paddingTop: 8, paddingBottom: 30, gap: 22 }, topBar: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, close: { width: 42, height: 42, borderRadius: 21, alignItems: "center", justifyContent: "center" }, modalTitle: { fontSize: 16, lineHeight: 21, fontWeight: "800" }, topSpacer: { width: 42 }, editor: { borderWidth: 1, borderRadius: 26, padding: 18 }, prompt: { fontSize: 24, lineHeight: 30, fontWeight: "800", letterSpacing: -0.5 }, helper: { fontSize: 13, lineHeight: 18, marginTop: 3 }, input: { height: 170, borderWidth: 1, borderRadius: 20, marginTop: 18, padding: 15, textAlignVertical: "top", fontSize: 17, lineHeight: 25 }, counter: { alignSelf: "flex-end", fontSize: 11, lineHeight: 15, marginTop: 7 }, sectionLabel: { fontSize: 15, lineHeight: 20, fontWeight: "800", marginBottom: 4 }, sectionHelper: { fontSize: 12, lineHeight: 17, marginBottom: 10 }, horizontal: { gap: 8, paddingRight: 18 }, save: { minHeight: 54, borderRadius: 27, marginTop: 2, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 9 }, saveText: { fontSize: 16, lineHeight: 21, fontWeight: "900" } });
