import { useLocalSearchParams, useRouter } from "expo-router";
import { useState } from "react";
import { FlatList, KeyboardAvoidingView, Platform, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { AppIcon } from "@/components/app-icon"; import { AppScreen } from "@/components/app-screen"; import { MoodChip } from "@/components/mood-chip"; import { useAppTheme } from "@/hooks/use-app-theme"; import type { Mood } from "@/lib/domain"; import { useHappy } from "@/lib/happy-store";
import { haptic } from "@/lib/haptics";
const moods: Mood[] = ["sunny", "peaceful", "proud", "connected"];
export default function ComposeScreen() {
  const router = useRouter(); const params = useLocalSearchParams<{ podId?: string }>(); const { colors } = useAppTheme(); const { state, addMoment } = useHappy(); const [text, setText] = useState(""); const [mood, setMood] = useState<Mood>("sunny"); const [podId, setPodId] = useState<string | undefined>(params.podId);
  function save() { if (!text.trim()) return; addMoment({ text, mood, podId }); haptic.success(); router.back(); }
  return <AppScreen edges={["top", "bottom", "left", "right"]}><KeyboardAvoidingView behavior={Platform.OS === "ios" ? "padding" : undefined} style={styles.flex}><View style={styles.container}><View style={styles.topBar}><Pressable accessibilityRole="button" accessibilityLabel="Close" onPress={() => router.back()} style={({ pressed }) => [styles.close, { backgroundColor: colors.surfaceAlt, opacity: pressed ? 0.6 : 1 }]}><AppIcon name="close" size={21} color={colors.ink} /></Pressable><Text style={[styles.modalTitle, { color: colors.ink }]}>Keep this moment</Text><View style={styles.topSpacer} /></View>
    <View style={[styles.editor, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text style={[styles.prompt, { color: colors.ink }]}>What felt good?</Text><Text style={[styles.helper, { color: colors.muted }]}>Write it like a note to your future self.</Text><TextInput autoFocus multiline value={text} onChangeText={setText} maxLength={800} placeholder="Today, I want to remember…" placeholderTextColor={colors.muted} style={[styles.input, { color: colors.ink, borderColor: colors.border, backgroundColor: colors.background }]} /><Text style={[styles.counter, { color: colors.muted }]}>{text.length}/800</Text></View>
    <View><Text style={[styles.sectionLabel, { color: colors.ink }]}>How did it feel?</Text><FlatList horizontal data={moods} keyExtractor={(item) => item} showsHorizontalScrollIndicator={false} contentContainerStyle={styles.horizontal} renderItem={({ item }) => <MoodChip mood={item} selected={mood === item} onPress={() => setMood(item)} />} /></View>
    <View><Text style={[styles.sectionLabel, { color: colors.ink }]}>Who can see it?</Text><FlatList horizontal data={[{ id: "private", name: "Just me" }, ...state.pods.map((pod) => ({ id: pod.id, name: pod.name }))]} keyExtractor={(item) => item.id} contentContainerStyle={styles.horizontal} showsHorizontalScrollIndicator={false} renderItem={({ item }) => { const selected = item.id === "private" ? !podId : podId === item.id; return <Pressable onPress={() => setPodId(item.id === "private" ? undefined : item.id)} style={[styles.podChip, { backgroundColor: selected ? colors.primarySoft : colors.surface, borderColor: selected ? colors.primary : colors.border }]}><AppIcon name={item.id === "private" ? "lock-closed-outline" : "people-outline"} size={17} color={selected ? colors.ink : colors.muted} /><Text style={[styles.podLabel, { color: selected ? colors.ink : colors.muted }]}>{item.name}</Text></Pressable>; }} /></View>
    <Pressable accessibilityRole="button" accessibilityState={{ disabled: !text.trim() }} disabled={!text.trim()} onPress={save} style={({ pressed }) => [styles.save, { backgroundColor: text.trim() ? colors.primary : colors.border, opacity: pressed ? 0.76 : 1 }]}><Text style={[styles.saveText, { color: colors.ink }]}>Save moment</Text><AppIcon name="sparkles" size={19} color={colors.ink} /></Pressable>
  </View></KeyboardAvoidingView></AppScreen>;
}
const styles = StyleSheet.create({ flex: { flex: 1 }, container: { flex: 1, paddingHorizontal: 18, paddingTop: 8, paddingBottom: 12, gap: 22 }, topBar: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, close: { width: 42, height: 42, borderRadius: 21, alignItems: "center", justifyContent: "center" }, modalTitle: { fontSize: 16, lineHeight: 21, fontWeight: "800" }, topSpacer: { width: 42 }, editor: { borderWidth: 1, borderRadius: 26, padding: 18 }, prompt: { fontSize: 24, lineHeight: 30, fontWeight: "800", letterSpacing: -0.5 }, helper: { fontSize: 13, lineHeight: 18, marginTop: 3 }, input: { height: 190, borderWidth: 1, borderRadius: 20, marginTop: 18, padding: 15, textAlignVertical: "top", fontSize: 17, lineHeight: 25 }, counter: { alignSelf: "flex-end", fontSize: 11, lineHeight: 15, marginTop: 7 }, sectionLabel: { fontSize: 15, lineHeight: 20, fontWeight: "800", marginBottom: 10 }, horizontal: { gap: 8, paddingRight: 18 }, podChip: { minHeight: 42, paddingHorizontal: 13, borderRadius: 21, borderWidth: 1, flexDirection: "row", alignItems: "center", gap: 7 }, podLabel: { fontSize: 13, lineHeight: 18, fontWeight: "700" }, save: { minHeight: 54, borderRadius: 27, marginTop: "auto", flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 9 }, saveText: { fontSize: 16, lineHeight: 21, fontWeight: "900" } });
