import { useRouter } from "expo-router";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { AppIcon } from "@/components/app-icon";
import { AppScreen } from "@/components/app-screen";
import { useAppTheme } from "@/hooks/use-app-theme";

const sections = [
  ["Information HappyMe handles", "HappyMe stores the email address and display name you provide; your private moments, moods, tags, favorites, pod memberships, reactions, kindness messages, friend connections, block choices, reports, support requests, and app preferences. Authentication tokens are stored in the device keychain. A local cache helps the app remain responsive when connectivity is limited."],
  ["How it is used", "This information is used only to provide your account, synchronize your devices, deliver the sharing you choose, operate private pods and friendships, respond to safety or support requests, prevent abuse, and maintain the service. HappyMe does not sell reflection data or use it for advertising."],
  ["Who can see content", "Private moments are visible only to you. A moment assigned to a pod is visible to current members of that pod. Kindness messages are visible to their sender and recipient. Blocks hide shared content between the affected accounts. Authorized service administrators may review reports and support requests when necessary for safety and support."],
  ["Service providers", "HappyMe uses Supabase for authentication, database storage, synchronization, and realtime updates; Vercel for the public invitation and policy website; Expo/EAS for application builds and updates; and Apple for App Store distribution and device services. These providers process information only to deliver their respective services."],
  ["Retention and deletion", "Information is retained while your account is active. Settings → Delete My Account permanently removes the authentication identity and associated HappyMe profile, moments, pod ownership and membership, reactions, kindness messages, friendships, blocks, reports, and support requests. Deletion cannot be undone."],
  ["Your choices", "You can export a portable backup, remove individual moments, delete all moments, leave or manage pods, block people, report shared content, sign out, or permanently delete your account in the app."],
  ["Security and children", "HappyMe uses encrypted network connections, private access policies, and device keychain storage. No service can guarantee absolute security. HappyMe is not directed to children under 13, and people under the applicable digital-consent age should use it only with a parent or guardian."],
  ["Changes", "This notice may change as HappyMe evolves. Material changes will be reflected here with a revised effective date. Effective August 29, 2026."],
] as const;

export default function PrivacyScreen() {
  const router = useRouter(); const { colors } = useAppTheme();
  return <AppScreen edges={["top", "bottom", "left", "right"]}><ScrollView contentContainerStyle={styles.content}><View style={styles.topBar}><Pressable onPress={() => router.canGoBack() ? router.back() : router.replace("/" as never)} style={[styles.circle, { backgroundColor: colors.surface, borderColor: colors.border }]}><AppIcon name="chevron-back" size={21} color={colors.ink} /></Pressable><Text style={[styles.topTitle, { color: colors.ink }]}>Privacy</Text><View style={styles.circle} /></View><View style={[styles.icon, { backgroundColor: colors.primarySoft }]}><AppIcon name="lock-closed" size={32} color={colors.coral} /></View><Text style={[styles.title, { color: colors.ink }]}>HappyMe Privacy Notice</Text><Text style={[styles.intro, { color: colors.muted }]}>A plain-language explanation of what is stored, why it is needed, and the controls available to you.</Text>{sections.map(([heading, body]) => <View key={heading} style={[styles.section, { borderColor: colors.border }]}><Text style={[styles.heading, { color: colors.ink }]}>{heading}</Text><Text style={[styles.body, { color: colors.muted }]}>{body}</Text></View>)}</ScrollView></AppScreen>;
}

const styles = StyleSheet.create({ content: { paddingHorizontal: 20, paddingTop: 8, paddingBottom: 40 }, topBar: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 22 }, circle: { width: 44, height: 44, borderRadius: 22, borderWidth: 1, alignItems: "center", justifyContent: "center" }, topTitle: { fontSize: 14, lineHeight: 19, fontWeight: "900" }, icon: { width: 68, height: 68, borderRadius: 24, alignSelf: "center", alignItems: "center", justifyContent: "center" }, title: { fontSize: 28, lineHeight: 35, fontWeight: "900", textAlign: "center", marginTop: 15 }, intro: { fontSize: 14, lineHeight: 21, textAlign: "center", marginTop: 7, marginBottom: 8 }, section: { borderTopWidth: StyleSheet.hairlineWidth, paddingTop: 17, marginTop: 17 }, heading: { fontSize: 16, lineHeight: 22, fontWeight: "900" }, body: { fontSize: 13, lineHeight: 20, marginTop: 5 } });
