import { useLocalSearchParams, useRouter } from "expo-router";
import { useState } from "react";
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Switch, Text, TextInput, View } from "react-native";
import { AppIcon } from "@/components/app-icon";
import { AppScreen } from "@/components/app-screen";
import { useAppTheme } from "@/hooks/use-app-theme";
import { useAuth } from "@/lib/auth";
import { haptic } from "@/lib/haptics";
import { useHappy } from "@/lib/happy-store";
import { supabase } from "@/lib/supabase";

const reasons = [{ value: "harassment", label: "Harassment or bullying" }, { value: "hate", label: "Hateful content" }, { value: "sexual", label: "Sexual content" }, { value: "violence", label: "Violence or threats" }, { value: "self_harm", label: "Self-harm concern" }, { value: "spam", label: "Spam or impersonation" }, { value: "other", label: "Something else" }] as const;

export default function ReportScreen() {
  const params = useLocalSearchParams<{ userId: string; momentId?: string; podId?: string }>(); const router = useRouter(); const { colors } = useAppTheme(); const { user } = useAuth(); const { refresh } = useHappy();
  const [reason, setReason] = useState<(typeof reasons)[number]["value"]>("harassment"); const [details, setDetails] = useState(""); const [alsoBlock, setAlsoBlock] = useState(true); const [sending, setSending] = useState(false);
  async function submit() { if (!user || !params.userId || sending) return; setSending(true); const report = await supabase.from("reports").insert({ reporter_id: user.id, reported_user_id: params.userId, moment_id: params.momentId ?? null, pod_id: params.podId ?? null, reason, details: details.trim() || null }); if (!report.error && alsoBlock) await supabase.from("blocks").upsert({ blocker_id: user.id, blocked_id: params.userId }); setSending(false); if (report.error) { Alert.alert("Report not sent", "Please check your connection and try again."); return; } await refresh(); haptic.success(); Alert.alert("Thank you", "The report was saved for review. The reported person has been hidden from your HappyMe experience.", [{ text: "Done", onPress: () => router.replace("/" as never) }]); }
  return <AppScreen edges={["top", "bottom", "left", "right"]}><ScrollView contentContainerStyle={styles.content}><View style={styles.topBar}><Pressable onPress={() => router.back()} style={[styles.circle, { backgroundColor: colors.surface, borderColor: colors.border }]}><AppIcon name="chevron-back" size={21} color={colors.ink} /></Pressable><Text style={[styles.topTitle, { color: colors.ink }]}>Report or block</Text><View style={styles.circle} /></View><View style={[styles.shield, { backgroundColor: colors.primarySoft }]}><AppIcon name="shield-checkmark" size={33} color={colors.coral} /></View><Text style={[styles.title, { color: colors.ink }]}>Help keep HappyMe gentle.</Text><Text style={[styles.subtitle, { color: colors.muted }]}>Reports are private. If someone is in immediate danger, contact local emergency services rather than waiting for an app response.</Text><View style={[styles.group, { backgroundColor: colors.surface, borderColor: colors.border }]}>{reasons.map((item, index) => <Pressable key={item.value} onPress={() => setReason(item.value)} style={[styles.reason, index > 0 && { borderTopColor: colors.border, borderTopWidth: StyleSheet.hairlineWidth }]}><View style={[styles.radio, { borderColor: reason === item.value ? colors.coral : colors.border }]}>{reason === item.value ? <View style={[styles.radioFill, { backgroundColor: colors.coral }]} /> : null}</View><Text style={[styles.reasonText, { color: colors.ink }]}>{item.label}</Text></Pressable>)}</View><TextInput multiline maxLength={500} value={details} onChangeText={setDetails} placeholder="Optional details for the review team" placeholderTextColor={colors.muted} style={[styles.details, { backgroundColor: colors.surface, borderColor: colors.border, color: colors.ink }]} /><View style={[styles.blockRow, { backgroundColor: colors.surfaceAlt }]}><View style={styles.blockCopy}><Text style={[styles.blockTitle, { color: colors.ink }]}>Block this person</Text><Text style={[styles.blockBody, { color: colors.muted }]}>Hide their shared moments and stop direct kindness messages.</Text></View><Switch value={alsoBlock} onValueChange={setAlsoBlock} trackColor={{ false: colors.border, true: colors.primary }} /></View><Pressable onPress={submit} disabled={sending} style={[styles.submit, { backgroundColor: colors.coral }]}>{sending ? <ActivityIndicator color="#FFFFFF" /> : <><AppIcon name="flag" size={19} color="#FFFFFF" /><Text style={styles.submitText}>Submit report</Text></>}</Pressable></ScrollView></AppScreen>;
}
const styles = StyleSheet.create({ content: { paddingHorizontal: 20, paddingTop: 8, paddingBottom: 36 }, topBar: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 24 }, circle: { width: 44, height: 44, borderRadius: 22, borderWidth: 1, alignItems: "center", justifyContent: "center" }, topTitle: { fontSize: 14, lineHeight: 19, fontWeight: "900" }, shield: { width: 68, height: 68, borderRadius: 24, alignSelf: "center", alignItems: "center", justifyContent: "center" }, title: { fontSize: 27, lineHeight: 34, fontWeight: "900", textAlign: "center", marginTop: 16 }, subtitle: { fontSize: 13, lineHeight: 20, textAlign: "center", marginTop: 7 }, group: { borderWidth: 1, borderRadius: 22, paddingHorizontal: 13, marginTop: 22 }, reason: { minHeight: 50, flexDirection: "row", alignItems: "center", gap: 11 }, radio: { width: 20, height: 20, borderWidth: 2, borderRadius: 10, alignItems: "center", justifyContent: "center" }, radioFill: { width: 10, height: 10, borderRadius: 5 }, reasonText: { fontSize: 14, lineHeight: 19, fontWeight: "700" }, details: { minHeight: 110, borderWidth: 1, borderRadius: 20, marginTop: 14, padding: 14, textAlignVertical: "top", fontSize: 14, lineHeight: 21 }, blockRow: { borderRadius: 20, padding: 15, flexDirection: "row", alignItems: "center", gap: 12, marginTop: 14 }, blockCopy: { flex: 1 }, blockTitle: { fontSize: 14, lineHeight: 19, fontWeight: "900" }, blockBody: { fontSize: 11, lineHeight: 16, marginTop: 2 }, submit: { minHeight: 54, borderRadius: 27, marginTop: 18, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8 }, submitText: { color: "#FFFFFF", fontSize: 15, lineHeight: 20, fontWeight: "900" } });
