import { useRouter } from "expo-router";
import { useState } from "react";
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { AppIcon } from "@/components/app-icon";
import { AppScreen } from "@/components/app-screen";
import { useAppTheme } from "@/hooks/use-app-theme";
import { useAuth } from "@/lib/auth";
import { haptic } from "@/lib/haptics";
import { supabase } from "@/lib/supabase";

export default function SupportScreen() {
  const router = useRouter(); const { colors } = useAppTheme(); const { user } = useAuth();
  const [email, setEmail] = useState(""); const [message, setMessage] = useState(""); const [sending, setSending] = useState(false);
  const contactEmail = user?.email ?? email.trim().toLowerCase(); const canSend = message.trim().length > 0 && Boolean(user || contactEmail.includes("@"));
  async function send() { if (!canSend || sending) return; setSending(true); const { error } = await supabase.from("support_requests").insert({ user_id: user?.id ?? null, email: contactEmail, message: message.trim() }); setSending(false); if (error) { Alert.alert("Message not sent", "Please check your connection and try again."); return; } setMessage(""); haptic.success(); Alert.alert("Message received", "Thank you. Your private support request has been saved."); }
  return <AppScreen edges={["top", "bottom", "left", "right"]}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={styles.content}><View style={styles.topBar}><Pressable onPress={() => router.canGoBack() ? router.back() : router.replace("/" as never)} style={[styles.circle, { backgroundColor: colors.surface, borderColor: colors.border }]}><AppIcon name="chevron-back" size={21} color={colors.ink} /></Pressable><Text style={[styles.topTitle, { color: colors.ink }]}>Safety & support</Text><View style={styles.circle} /></View><View style={[styles.icon, { backgroundColor: colors.primarySoft }]}><AppIcon name="heart-circle" size={36} color={colors.coral} /></View><Text style={[styles.title, { color: colors.ink }]}>We want HappyMe to feel safe.</Text><Text style={[styles.body, { color: colors.muted }]}>Use Report or Block on a shared moment for community-safety concerns. Use this private form for account, privacy, invitation, or technical help.</Text><View style={[styles.notice, { backgroundColor: colors.surfaceAlt }]}><AppIcon name="alert-circle-outline" size={20} color={colors.coral} /><Text style={[styles.noticeText, { color: colors.muted }]}>This form is not monitored as an emergency service. If someone is in immediate danger, contact local emergency services.</Text></View>{!user ? <TextInput autoCapitalize="none" autoCorrect={false} keyboardType="email-address" value={email} onChangeText={setEmail} placeholder="Your email address" placeholderTextColor={colors.muted} style={[styles.emailInput, { backgroundColor: colors.surface, borderColor: colors.border, color: colors.ink }]} /> : null}<TextInput multiline maxLength={1000} value={message} onChangeText={setMessage} placeholder="How can we help?" placeholderTextColor={colors.muted} style={[styles.input, { backgroundColor: colors.surface, borderColor: colors.border, color: colors.ink }]} /><Pressable onPress={send} disabled={!canSend || sending} style={[styles.send, { backgroundColor: canSend ? colors.primary : colors.border }]}>{sending ? <ActivityIndicator color={colors.ink} /> : <><Text style={[styles.sendText, { color: colors.ink }]}>Send support request</Text><AppIcon name="send" size={18} color={colors.ink} /></>}</Pressable><View style={[styles.policy, { borderColor: colors.border }]}><Text style={[styles.policyTitle, { color: colors.ink }]}>Your controls</Text><Text style={[styles.policyText, { color: colors.muted }]}>You can export your data, block people, report shared content, delete every moment, or permanently delete your account from Settings.</Text></View></ScrollView></AppScreen>;
}

const styles = StyleSheet.create({ content: { paddingHorizontal: 20, paddingTop: 8, paddingBottom: 36 }, topBar: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 24 }, circle: { width: 44, height: 44, borderRadius: 22, borderWidth: 1, alignItems: "center", justifyContent: "center" }, topTitle: { fontSize: 14, lineHeight: 19, fontWeight: "900" }, icon: { width: 72, height: 72, borderRadius: 25, alignSelf: "center", alignItems: "center", justifyContent: "center" }, title: { fontSize: 28, lineHeight: 35, fontWeight: "900", textAlign: "center", marginTop: 16 }, body: { fontSize: 14, lineHeight: 21, textAlign: "center", marginTop: 7 }, notice: { borderRadius: 19, padding: 14, flexDirection: "row", alignItems: "flex-start", gap: 10, marginTop: 20 }, noticeText: { flex: 1, fontSize: 11, lineHeight: 17 }, emailInput: { minHeight: 53, borderWidth: 1, borderRadius: 18, paddingHorizontal: 15, marginTop: 16, fontSize: 15, lineHeight: 21 }, input: { minHeight: 160, borderWidth: 1, borderRadius: 22, padding: 15, marginTop: 12, textAlignVertical: "top", fontSize: 15, lineHeight: 22 }, send: { minHeight: 54, borderRadius: 27, marginTop: 14, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8 }, sendText: { fontSize: 14, lineHeight: 19, fontWeight: "900" }, policy: { borderWidth: 1, borderRadius: 20, padding: 16, marginTop: 18 }, policyTitle: { fontSize: 14, lineHeight: 19, fontWeight: "900" }, policyText: { fontSize: 12, lineHeight: 18, marginTop: 4 } });
