import { useRouter } from "expo-router";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { AppIcon } from "@/components/app-icon";
import { AppScreen } from "@/components/app-screen";
import { useAppTheme } from "@/hooks/use-app-theme";

const rules = [
  ["Use HappyMe kindly", "Do not threaten, harass, impersonate, exploit, spam, or share hateful, sexual, violent, illegal, or privacy-invasive content. Never post another person’s sensitive information without permission."],
  ["Private does not mean consequence-free", "Pods are intentionally small and private, but members can report shared content. HappyMe may investigate reports, restrict features, remove content, suspend accounts, preserve evidence when legally required, or contact appropriate authorities when necessary for safety."],
  ["Protect your account", "Use accurate account information and a strong unique password. You are responsible for activity performed through your account and for sharing pod invitations only with people you intend to include."],
  ["Your content", "You keep ownership of your original content. You grant HappyMe a limited license to store, synchronize, display, and process it only as needed to operate the features you choose. You must have the right to share anything you submit."],
  ["Health and emergencies", "HappyMe is a reflection and connection tool, not medical, mental-health, crisis, or emergency care. Do not rely on it to prevent harm or reach emergency services."],
  ["Availability", "The service may change, pause, or experience errors. Keep exports of information you cannot afford to lose. HappyMe is provided without promises that it will always be uninterrupted or error-free."],
  ["Ending use", "You can stop using HappyMe or delete your account at any time. These terms may be updated as the service changes. Continued use after an update means you accept the revised terms. Effective August 29, 2026."],
] as const;

export default function TermsScreen() {
  const router = useRouter(); const { colors } = useAppTheme();
  return <AppScreen edges={["top", "bottom", "left", "right"]}><ScrollView contentContainerStyle={styles.content}><View style={styles.topBar}><Pressable onPress={() => router.canGoBack() ? router.back() : router.replace("/" as never)} style={[styles.circle, { backgroundColor: colors.surface, borderColor: colors.border }]}><AppIcon name="chevron-back" size={21} color={colors.ink} /></Pressable><Text style={[styles.topTitle, { color: colors.ink }]}>Terms</Text><View style={styles.circle} /></View><View style={[styles.icon, { backgroundColor: colors.primarySoft }]}><AppIcon name="heart" size={32} color={colors.coral} /></View><Text style={[styles.title, { color: colors.ink }]}>Terms & Community Standards</Text><Text style={[styles.intro, { color: colors.muted }]}>HappyMe is built for small, trusted circles. These standards protect that feeling.</Text>{rules.map(([heading, body], index) => <View key={heading} style={[styles.rule, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={[styles.number, { backgroundColor: colors.primary }]}><Text style={[styles.numberText, { color: colors.ink }]}>{index + 1}</Text></View><View style={styles.ruleCopy}><Text style={[styles.heading, { color: colors.ink }]}>{heading}</Text><Text style={[styles.body, { color: colors.muted }]}>{body}</Text></View></View>)}</ScrollView></AppScreen>;
}

const styles = StyleSheet.create({ content: { paddingHorizontal: 20, paddingTop: 8, paddingBottom: 40 }, topBar: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 22 }, circle: { width: 44, height: 44, borderRadius: 22, borderWidth: 1, alignItems: "center", justifyContent: "center" }, topTitle: { fontSize: 15, lineHeight: 22, fontWeight: "900" }, icon: { width: 68, height: 68, borderRadius: 24, alignSelf: "center", alignItems: "center", justifyContent: "center" }, title: { fontSize: 28, lineHeight: 35, fontWeight: "900", textAlign: "center", marginTop: 15 }, intro: { fontSize: 15, lineHeight: 21, textAlign: "center", marginTop: 7, marginBottom: 8 }, rule: { borderWidth: 1, borderRadius: 22, padding: 15, flexDirection: "row", alignItems: "flex-start", gap: 12, marginTop: 12 }, number: { width: 30, height: 30, borderRadius: 11, alignItems: "center", justifyContent: "center" }, numberText: { fontSize: 15, lineHeight: 20, fontWeight: "900" }, ruleCopy: { flex: 1 }, heading: { fontSize: 15, lineHeight: 20, fontWeight: "900" }, body: { fontSize: 15, lineHeight: 21, marginTop: 4 } });
