import { Pressable, StyleSheet, Text, View } from "react-native";
import { AppIcon, type AppIconName } from "@/components/app-icon";
import { useAppTheme } from "@/hooks/use-app-theme";

export function AppHeader({ eyebrow, title, subtitle, actionIcon, onAction, actionLabel }: { eyebrow?: string; title: string; subtitle?: string; actionIcon?: AppIconName; onAction?: () => void; actionLabel?: string }) {
  const { colors } = useAppTheme();
  return <View style={styles.row}><View style={styles.copy}>{eyebrow ? <View style={styles.eyebrowRow}><View style={[styles.sunMark, { backgroundColor: colors.primary }]}><View style={[styles.sunCore, { backgroundColor: colors.ink }]} /></View><Text style={[styles.eyebrow, { color: colors.coral }]}>{eyebrow}</Text></View> : null}<Text style={[styles.title, { color: colors.ink }]}>{title}</Text>{subtitle ? <Text style={[styles.subtitle, { color: colors.muted }]}>{subtitle}</Text> : null}</View>{actionIcon && onAction ? <Pressable accessibilityRole="button" accessibilityLabel={actionLabel} onPress={onAction} style={({ pressed }) => [styles.action, { backgroundColor: colors.surface, borderColor: colors.border, opacity: pressed ? 0.65 : 1 }]}><AppIcon name={actionIcon} size={22} color={colors.ink} /></Pressable> : null}</View>;
}
const styles = StyleSheet.create({ row: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between", gap: 16 }, copy: { flex: 1 }, eyebrowRow: { flexDirection: "row", alignItems: "center", gap: 7, marginBottom: 5 }, sunMark: { width: 14, height: 14, borderRadius: 7, alignItems: "center", justifyContent: "center" }, sunCore: { width: 4, height: 4, borderRadius: 2 }, eyebrow: { fontSize: 15, lineHeight: 20, fontWeight: "800", letterSpacing: 1.2, textTransform: "uppercase" }, title: { fontSize: 34, lineHeight: 40, fontWeight: "800", letterSpacing: -1.1 }, subtitle: { fontSize: 15, lineHeight: 21, marginTop: 5, maxWidth: 310 }, action: { width: 44, height: 44, borderRadius: 22, borderWidth: 1, alignItems: "center", justifyContent: "center" } });
