import { useMemo, useState } from "react";
import { FlatList, Pressable, StyleSheet, Text, View } from "react-native";
import { AppHeader } from "@/components/app-header";
import { AppIcon } from "@/components/app-icon";
import { AppScreen } from "@/components/app-screen";
import { EmptyState } from "@/components/empty-state";
import { MomentCard } from "@/components/moment-card";
import { useAppTheme } from "@/hooks/use-app-theme";
import { dayKey, formatMonth, getMonthCells, isSameMonth, uniqueDayCount } from "@/lib/date";
import { useHappy } from "@/lib/happy-store";

const weekDays = ["S", "M", "T", "W", "T", "F", "S"];
export default function GardenScreen() {
  const { colors } = useAppTheme(); const { state } = useHappy();
  const [month, setMonth] = useState(() => new Date(new Date().getFullYear(), new Date().getMonth(), 1)); const [selectedDay, setSelectedDay] = useState<string | null>(null);
  const monthMoments = useMemo(() => state.moments.filter((moment) => isSameMonth(moment.createdAt, month)), [state.moments, month]);
  const momentsByDay = useMemo(() => { const map = new Map<string, number>(); monthMoments.forEach((moment) => map.set(dayKey(moment.createdAt), (map.get(dayKey(moment.createdAt)) ?? 0) + 1)); return map; }, [monthMoments]);
  const visibleMoments = useMemo(() => [...monthMoments].filter((moment) => !selectedDay || dayKey(moment.createdAt) === selectedDay).sort((a, b) => b.createdAt.localeCompare(a.createdAt)), [monthMoments, selectedDay]);
  const cells = getMonthCells(month);
  function changeMonth(offset: number) { setMonth((current) => new Date(current.getFullYear(), current.getMonth() + offset, 1)); setSelectedDay(null); }
  const header = <View style={styles.headerContent}><AppHeader eyebrow="Your living archive" title="Joy Garden" subtitle="Every bright dot is a moment you chose to keep." />
    <View style={[styles.calendar, { backgroundColor: colors.surface, borderColor: colors.border, shadowColor: colors.shadow }]}><View style={styles.monthRow}><Pressable accessibilityRole="button" accessibilityLabel="Previous month" onPress={() => changeMonth(-1)} style={({ pressed }) => [styles.arrow, { backgroundColor: colors.surfaceAlt, opacity: pressed ? 0.6 : 1 }]}><AppIcon name="chevron-back" size={19} color={colors.ink} /></Pressable><View style={styles.monthCopy}><Text style={[styles.monthTitle, { color: colors.ink }]}>{formatMonth(month)}</Text><Text style={[styles.monthSubtitle, { color: colors.muted }]}>{uniqueDayCount(monthMoments.map((moment) => moment.createdAt))} days with something good</Text></View><Pressable accessibilityRole="button" accessibilityLabel="Next month" onPress={() => changeMonth(1)} style={({ pressed }) => [styles.arrow, { backgroundColor: colors.surfaceAlt, opacity: pressed ? 0.6 : 1 }]}><AppIcon name="chevron-forward" size={19} color={colors.ink} /></Pressable></View>
      <View style={styles.weekRow}>{weekDays.map((day, index) => <Text key={`${day}-${index}`} style={[styles.weekDay, { color: colors.muted }]}>{day}</Text>)}</View>
      <View style={styles.grid}>{cells.map((date, index) => { if (!date) return <View key={`empty-${index}`} style={styles.dayCell} />; const key = dayKey(date); const count = momentsByDay.get(key) ?? 0; const selected = selectedDay === key; const today = key === dayKey(new Date()); return <Pressable key={key} accessibilityRole="button" accessibilityLabel={`${date.toLocaleDateString([], { month: "long", day: "numeric" })}, ${count} moments`} onPress={() => setSelectedDay((current) => current === key ? null : key)} style={({ pressed }) => [styles.dayCell, { opacity: pressed ? 0.55 : 1 }]}><View style={[styles.dayNumberWrap, selected && { backgroundColor: colors.ink }, today && !selected && { borderColor: colors.primary, borderWidth: 1.5 }]}><Text style={[styles.dayNumber, { color: selected ? colors.background : colors.ink }]}>{date.getDate()}</Text></View><View style={styles.dots}>{Array.from({ length: Math.min(count, 3) }).map((_, dot) => <View key={dot} style={[styles.dot, { backgroundColor: [colors.primary, colors.coral, colors.lavender][dot] }]} />)}</View></Pressable>; })}</View>
    </View>
    <View style={styles.archiveTitleRow}><View><Text style={[styles.archiveTitle, { color: colors.ink }]}>{selectedDay ? "That day" : "This month"}</Text><Text style={[styles.archiveSubtitle, { color: colors.muted }]}>{visibleMoments.length} {visibleMoments.length === 1 ? "moment" : "moments"}</Text></View>{selectedDay ? <Pressable onPress={() => setSelectedDay(null)} style={({ pressed }) => ({ opacity: pressed ? 0.55 : 1 })}><Text style={[styles.clear, { color: colors.coral }]}>Show all</Text></Pressable> : null}</View>
  </View>;
  return <AppScreen><FlatList data={visibleMoments} keyExtractor={(item) => item.id} contentContainerStyle={styles.list} ListHeaderComponent={header} ListEmptyComponent={<EmptyState icon="leaf-outline" title="Nothing planted here yet" body="Choose another month or add a moment from Today." />} ItemSeparatorComponent={() => <View style={styles.separator} />} renderItem={({ item }) => <MomentCard moment={item} authorName={state.members.find((member) => member.id === item.authorId)?.name ?? "Someone"} podName={state.pods.find((pod) => pod.id === item.podId)?.name} />} showsVerticalScrollIndicator={false} /></AppScreen>;
}
const styles = StyleSheet.create({ list: { paddingHorizontal: 18, paddingBottom: 32 }, headerContent: { paddingTop: 12, paddingBottom: 16, gap: 22 }, calendar: { borderRadius: 26, borderWidth: 1, padding: 17, shadowOpacity: 0.06, shadowRadius: 15, shadowOffset: { width: 0, height: 6 }, elevation: 2 }, monthRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, arrow: { width: 40, height: 40, borderRadius: 20, alignItems: "center", justifyContent: "center" }, monthCopy: { alignItems: "center" }, monthTitle: { fontSize: 18, lineHeight: 24, fontWeight: "800" }, monthSubtitle: { fontSize: 11, lineHeight: 16, marginTop: 1 }, weekRow: { flexDirection: "row", marginTop: 20 }, weekDay: { width: "14.2857%", textAlign: "center", fontSize: 11, lineHeight: 15, fontWeight: "800" }, grid: { flexDirection: "row", flexWrap: "wrap", marginTop: 8 }, dayCell: { width: "14.2857%", height: 52, alignItems: "center", justifyContent: "flex-start", paddingTop: 3 }, dayNumberWrap: { width: 32, height: 32, borderRadius: 16, alignItems: "center", justifyContent: "center" }, dayNumber: { fontSize: 13, lineHeight: 17, fontWeight: "700" }, dots: { height: 8, flexDirection: "row", justifyContent: "center", gap: 2, marginTop: 3 }, dot: { width: 4, height: 4, borderRadius: 2 }, archiveTitleRow: { flexDirection: "row", alignItems: "flex-end", justifyContent: "space-between" }, archiveTitle: { fontSize: 22, lineHeight: 28, fontWeight: "800" }, archiveSubtitle: { fontSize: 13, lineHeight: 18, marginTop: 1 }, clear: { fontSize: 13, lineHeight: 18, fontWeight: "800" }, separator: { height: 13 } });
