import { useRouter } from "expo-router";
import { useMemo, useState } from "react";
import { FlatList, Pressable, StyleSheet, Text, View } from "react-native";
import { AppHeader } from "@/components/app-header"; import { AppIcon } from "@/components/app-icon"; import { AppScreen } from "@/components/app-screen"; import { EmptyState } from "@/components/empty-state"; import { MemberAvatar } from "@/components/member-avatar"; import { useAppTheme } from "@/hooks/use-app-theme"; import { formatMomentDate } from "@/lib/date"; import { useHappy } from "@/lib/happy-store";
export default function KindnessScreen() {
  const router = useRouter(); const { colors } = useAppTheme(); const { state, markEncouragementRead } = useHappy(); const [view, setView] = useState<"received" | "sent">("received");
  const items = useMemo(() => state.encouragements.filter((item) => view === "received" ? item.toMemberId === state.currentMemberId : item.fromMemberId === state.currentMemberId).sort((a, b) => b.createdAt.localeCompare(a.createdAt)), [state.encouragements, state.currentMemberId, view]);
  const unread = state.encouragements.filter((item) => item.toMemberId === state.currentMemberId && !item.read).length;
  const header = <View style={styles.header}><AppHeader eyebrow="Words that stay" title="Kindness" subtitle="Encouragement without likes, streaks, or pressure." actionIcon="create-outline" actionLabel="Write an encouragement" onAction={() => router.push("/encouragement/compose" as never)} /><View style={[styles.segment, { backgroundColor: colors.surfaceAlt }]}>{(["received", "sent"] as const).map((item) => <Pressable key={item} onPress={() => setView(item)} style={[styles.segmentItem, view === item && { backgroundColor: colors.surface }]}><Text style={[styles.segmentText, { color: view === item ? colors.ink : colors.muted }]}>{item === "received" ? `Received${unread ? ` (${unread})` : ""}` : "Sent"}</Text></Pressable>)}</View><View><Text style={[styles.sectionTitle, { color: colors.ink }]}>{view === "received" ? "Notes for you" : "Kindness you sent"}</Text><Text style={[styles.sectionSubtitle, { color: colors.muted }]}>Private, direct, and intentionally simple</Text></View></View>;
  return <AppScreen><FlatList data={items} keyExtractor={(item) => item.id} contentContainerStyle={styles.list} ListHeaderComponent={header} ListEmptyComponent={<EmptyState icon="heart-outline" title={view === "received" ? "A quiet inbox" : "Send the first note"} body="Kind words will collect here without becoming a popularity score." />} ItemSeparatorComponent={() => <View style={styles.separator} />} renderItem={({ item }) => { const personId = view === "received" ? item.fromMemberId : item.toMemberId; const person = state.members.find((member) => member.id === personId); const pod = state.pods.find((entry) => entry.id === item.podId); return <Pressable onPress={() => { if (!item.read && view === "received") void markEncouragementRead(item.id); }} style={({ pressed }) => [styles.note, { backgroundColor: item.read ? colors.surface : colors.primarySoft, borderColor: colors.border, opacity: pressed ? 0.72 : 1 }]}>{person ? <MemberAvatar member={person} size={43} /> : null}<View style={styles.noteCopy}><View style={styles.noteMeta}><Text style={[styles.person, { color: colors.ink }]}>{view === "received" ? person?.name : `To ${person?.name}`}</Text>{!item.read && view === "received" ? <View style={[styles.unreadDot, { backgroundColor: colors.coral }]} /> : null}</View><Text style={[styles.message, { color: colors.ink }]}>{item.message}</Text><Text style={[styles.date, { color: colors.muted }]}>{formatMomentDate(item.createdAt)}{pod ? `  ·  ${pod.name}` : ""}</Text></View></Pressable>; }} showsVerticalScrollIndicator={false} />
    <Pressable accessibilityRole="button" accessibilityLabel="Write an encouragement" onPress={() => router.push("/encouragement/compose" as never)} style={({ pressed }) => [styles.fab, { backgroundColor: colors.coral, shadowColor: colors.shadow, opacity: pressed ? 0.78 : 1 }]}><AppIcon name="heart" size={23} color="#FFFFFF" /></Pressable>
  </AppScreen>;
}
const styles = StyleSheet.create({ list: { paddingHorizontal: 18, paddingBottom: 100 }, header: { paddingTop: 12, paddingBottom: 16, gap: 22 }, segment: { minHeight: 44, borderRadius: 22, padding: 4, flexDirection: "row" }, segmentItem: { flex: 1, borderRadius: 18, alignItems: "center", justifyContent: "center", paddingVertical: 10 }, segmentText: { fontSize: 15, lineHeight: 21, fontWeight: "800" }, sectionTitle: { fontSize: 22, lineHeight: 28, fontWeight: "800" }, sectionSubtitle: { fontSize: 15, lineHeight: 21, marginTop: 2 }, separator: { height: 11 }, note: { borderRadius: 22, borderWidth: 1, padding: 16, flexDirection: "row", alignItems: "flex-start", gap: 12 }, noteCopy: { flex: 1 }, noteMeta: { flexDirection: "row", alignItems: "center", gap: 7 }, person: { fontSize: 15, lineHeight: 22, fontWeight: "800" }, unreadDot: { width: 7, height: 7, borderRadius: 4 }, message: { fontSize: 15, lineHeight: 22, marginTop: 6 }, date: { fontSize: 13, lineHeight: 20, marginTop: 9, fontWeight: "600" }, fab: { position: "absolute", right: 20, bottom: 20, width: 56, height: 56, borderRadius: 28, alignItems: "center", justifyContent: "center", shadowOpacity: 0.18, shadowRadius: 12, shadowOffset: { width: 0, height: 6 }, elevation: 5 } });
