import { useRouter } from "expo-router";
import { useMemo, useState } from "react";
import { FlatList, KeyboardAvoidingView, Modal, Platform, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { AppHeader } from "@/components/app-header"; import { AppIcon } from "@/components/app-icon"; import { AppScreen } from "@/components/app-screen"; import { EmptyState } from "@/components/empty-state"; import { MemberAvatar } from "@/components/member-avatar"; import { useAppTheme } from "@/hooks/use-app-theme"; import { haptic } from "@/lib/haptics"; import { useHappy } from "@/lib/happy-store";

const podColors = ["#F27C72", "#9E8BD8", "#72BFA3", "#6EA8D9"];
export default function PodsScreen() {
  const router = useRouter(); const { colors } = useAppTheme(); const { state, createPod, joinPodByCode } = useHappy();
  const [mode, setMode] = useState<"create" | "join" | null>(null); const [name, setName] = useState(""); const [description, setDescription] = useState(""); const [podColor, setPodColor] = useState(podColors[0]); const [code, setCode] = useState(""); const [error, setError] = useState("");
  const pods = useMemo(() => state.pods.filter((pod) => pod.memberIds.includes(state.currentMemberId)), [state.pods, state.currentMemberId]);
  function close() { setMode(null); setName(""); setDescription(""); setCode(""); setError(""); }
  function submitCreate() { if (!name.trim()) return; const id = createPod({ name, description: description || "A private place for small joys.", color: podColor }); haptic.success(); close(); router.push({ pathname: "/pod/[id]", params: { id } } as never); }
  function submitJoin() { if (!code.trim()) return; if (!joinPodByCode(code)) { setError("That code does not match a local invitation. Try KINDRED."); haptic.error(); return; } haptic.success(); close(); }
  const header = <View style={styles.header}><AppHeader eyebrow="Private by design" title="Your Pods" subtitle="Small circles for the people who root for you." /><View style={styles.actionRow}><Pressable onPress={() => setMode("create")} style={({ pressed }) => [styles.primaryAction, { backgroundColor: colors.ink, opacity: pressed ? 0.76 : 1 }]}><AppIcon name="add" size={20} color={colors.background} /><Text style={[styles.primaryActionText, { color: colors.background }]}>Create a pod</Text></Pressable><Pressable onPress={() => setMode("join")} style={({ pressed }) => [styles.secondaryAction, { backgroundColor: colors.surface, borderColor: colors.border, opacity: pressed ? 0.65 : 1 }]}><AppIcon name="key-outline" size={18} color={colors.ink} /><Text style={[styles.secondaryActionText, { color: colors.ink }]}>Join</Text></Pressable></View><View><Text style={[styles.sectionTitle, { color: colors.ink }]}>Close circles</Text><Text style={[styles.sectionSubtitle, { color: colors.muted }]}>{pods.length} private {pods.length === 1 ? "space" : "spaces"}</Text></View></View>;
  return <AppScreen><FlatList data={pods} keyExtractor={(item) => item.id} contentContainerStyle={styles.list} ListHeaderComponent={header} ListEmptyComponent={<EmptyState icon="people-outline" title="Make room for your people" body="Create a private pod or join one with an invitation code." />} ItemSeparatorComponent={() => <View style={styles.separator} />} renderItem={({ item }) => { const members = item.memberIds.map((id) => state.members.find((member) => member.id === id)).filter(Boolean); const momentCount = state.moments.filter((moment) => moment.podId === item.id).length; return <Pressable onPress={() => router.push({ pathname: "/pod/[id]", params: { id: item.id } } as never)} style={({ pressed }) => [styles.podCard, { backgroundColor: colors.surface, borderColor: colors.border, opacity: pressed ? 0.72 : 1 }]}><View style={[styles.podMark, { backgroundColor: item.color }]}><AppIcon name="people" size={23} color="#FFFFFF" /></View><View style={styles.podCopy}><Text style={[styles.podName, { color: colors.ink }]}>{item.name}</Text><Text numberOfLines={2} style={[styles.podDescription, { color: colors.muted }]}>{item.description}</Text><View style={styles.podMeta}><View style={styles.avatarStack}>{members.slice(0, 4).map((member, index) => member ? <View key={member.id} style={{ marginLeft: index === 0 ? 0 : -9 }}><MemberAvatar member={member} size={29} /></View> : null)}</View><Text style={[styles.count, { color: colors.muted }]}>{momentCount} {momentCount === 1 ? "moment" : "moments"}</Text></View></View><AppIcon name="chevron-forward" size={19} color={colors.muted} /></Pressable>; }} showsVerticalScrollIndicator={false} />
    <Modal visible={mode !== null} transparent animationType="slide" onRequestClose={close}><KeyboardAvoidingView behavior={Platform.OS === "ios" ? "padding" : undefined} style={styles.modalBackdrop}><Pressable style={StyleSheet.absoluteFill} onPress={close} /><View style={[styles.sheet, { backgroundColor: colors.background }]}><View style={[styles.handle, { backgroundColor: colors.border }]} /><View style={styles.sheetTitleRow}><View><Text style={[styles.sheetTitle, { color: colors.ink }]}>{mode === "create" ? "Create a private pod" : "Join a pod"}</Text><Text style={[styles.sheetSubtitle, { color: colors.muted }]}>{mode === "create" ? "Keep it small, warm, and intentional." : "Enter the invitation code you received."}</Text></View><Pressable onPress={close} style={[styles.sheetClose, { backgroundColor: colors.surfaceAlt }]}><AppIcon name="close" size={20} color={colors.ink} /></Pressable></View>{mode === "create" ? <><TextInput value={name} onChangeText={setName} placeholder="Pod name" placeholderTextColor={colors.muted} style={[styles.field, { color: colors.ink, backgroundColor: colors.surface, borderColor: colors.border }]} /><TextInput value={description} onChangeText={setDescription} placeholder="What is this circle for?" placeholderTextColor={colors.muted} multiline style={[styles.field, styles.descriptionField, { color: colors.ink, backgroundColor: colors.surface, borderColor: colors.border }]} /><View style={styles.colorRow}>{podColors.map((color) => <Pressable key={color} accessibilityLabel={`Use ${color} as pod color`} onPress={() => setPodColor(color)} style={[styles.colorChoice, { backgroundColor: color }, podColor === color && { borderColor: colors.ink, borderWidth: 3 }]} />)}</View><Pressable disabled={!name.trim()} onPress={submitCreate} style={[styles.sheetButton, { backgroundColor: name.trim() ? colors.primary : colors.border }]}><Text style={[styles.sheetButtonText, { color: colors.ink }]}>Create pod</Text></Pressable></> : <><TextInput autoCapitalize="characters" value={code} onChangeText={(value) => { setCode(value); setError(""); }} placeholder="INVITE CODE" placeholderTextColor={colors.muted} style={[styles.field, styles.codeField, { color: colors.ink, backgroundColor: colors.surface, borderColor: error ? colors.danger : colors.border }]} />{error ? <Text style={[styles.error, { color: colors.danger }]}>{error}</Text> : null}<Pressable disabled={!code.trim()} onPress={submitJoin} style={[styles.sheetButton, { backgroundColor: code.trim() ? colors.primary : colors.border }]}><Text style={[styles.sheetButtonText, { color: colors.ink }]}>Join pod</Text></Pressable></>}</View></KeyboardAvoidingView></Modal>
  </AppScreen>;
}
const styles = StyleSheet.create({ list: { paddingHorizontal: 18, paddingBottom: 32 }, header: { paddingTop: 12, paddingBottom: 16, gap: 22 }, actionRow: { flexDirection: "row", gap: 10 }, primaryAction: { flex: 1, minHeight: 50, borderRadius: 25, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8 }, primaryActionText: { fontSize: 14, lineHeight: 19, fontWeight: "900" }, secondaryAction: { minWidth: 104, minHeight: 50, borderRadius: 25, borderWidth: 1, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 7 }, secondaryActionText: { fontSize: 14, lineHeight: 19, fontWeight: "800" }, sectionTitle: { fontSize: 22, lineHeight: 28, fontWeight: "800" }, sectionSubtitle: { fontSize: 13, lineHeight: 18, marginTop: 2 }, separator: { height: 12 }, podCard: { minHeight: 150, borderWidth: 1, borderRadius: 24, padding: 17, flexDirection: "row", alignItems: "flex-start", gap: 13 }, podMark: { width: 48, height: 48, borderRadius: 17, alignItems: "center", justifyContent: "center" }, podCopy: { flex: 1 }, podName: { fontSize: 18, lineHeight: 24, fontWeight: "800" }, podDescription: { fontSize: 13, lineHeight: 19, marginTop: 4 }, podMeta: { flexDirection: "row", alignItems: "center", gap: 10, marginTop: 13 }, avatarStack: { flexDirection: "row" }, count: { fontSize: 12, lineHeight: 16, fontWeight: "700" }, modalBackdrop: { flex: 1, justifyContent: "flex-end", backgroundColor: "rgba(28,20,30,0.38)" }, sheet: { borderTopLeftRadius: 30, borderTopRightRadius: 30, paddingHorizontal: 20, paddingTop: 10, paddingBottom: 34, gap: 14 }, handle: { width: 42, height: 5, borderRadius: 3, alignSelf: "center", marginBottom: 7 }, sheetTitleRow: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between", gap: 14 }, sheetTitle: { fontSize: 24, lineHeight: 30, fontWeight: "800" }, sheetSubtitle: { fontSize: 13, lineHeight: 19, marginTop: 3 }, sheetClose: { width: 40, height: 40, borderRadius: 20, alignItems: "center", justifyContent: "center" }, field: { minHeight: 50, borderWidth: 1, borderRadius: 17, paddingHorizontal: 14, paddingVertical: 12, fontSize: 15, lineHeight: 21 }, descriptionField: { height: 90, textAlignVertical: "top" }, codeField: { textAlign: "center", fontSize: 19, letterSpacing: 3, fontWeight: "800", marginTop: 8 }, colorRow: { flexDirection: "row", gap: 12 }, colorChoice: { width: 40, height: 40, borderRadius: 20 }, sheetButton: { minHeight: 52, borderRadius: 26, alignItems: "center", justifyContent: "center", marginTop: 4 }, sheetButtonText: { fontSize: 15, lineHeight: 20, fontWeight: "900" }, error: { fontSize: 12, lineHeight: 18, textAlign: "center" } });
