import { useRouter } from "expo-router";
import { useMemo } from "react";
import { Alert, FlatList, Pressable, Share, StyleSheet, Switch, Text, View } from "react-native";
import { AppHeader } from "@/components/app-header"; import { AppIcon, type AppIconName } from "@/components/app-icon"; import { AppScreen } from "@/components/app-screen"; import { useAppTheme } from "@/hooks/use-app-theme"; import { uniqueDayCount } from "@/lib/date"; import type { AppearancePreference } from "@/lib/domain"; import { haptic } from "@/lib/haptics"; import { useHappy } from "@/lib/happy-store"; import { updateDailyReminder } from "@/lib/reminders";
import { useAuth } from "@/lib/auth";

function SettingsRow({ icon, title, detail, children, danger = false, onPress }: { icon: AppIconName; title: string; detail?: string; children?: React.ReactNode; danger?: boolean; onPress?: () => void }) {
  const { colors } = useAppTheme(); const content = <><View style={[styles.rowIcon, { backgroundColor: danger ? `${colors.danger}18` : colors.surfaceAlt }]}><AppIcon name={icon} size={19} color={danger ? colors.danger : colors.ink} /></View><View style={styles.rowCopy}><Text style={[styles.rowTitle, { color: danger ? colors.danger : colors.ink }]}>{title}</Text>{detail ? <Text style={[styles.rowDetail, { color: colors.muted }]}>{detail}</Text> : null}</View>{children ?? (onPress ? <AppIcon name="chevron-forward" size={18} color={colors.muted} /> : null)}</>;
  return onPress ? <Pressable onPress={onPress} style={({ pressed }) => [styles.row, { opacity: pressed ? 0.6 : 1 }]}>{content}</Pressable> : <View style={styles.row}>{content}</View>;
}

export default function ProfileScreen() {
  const router = useRouter(); const { colors, isDark } = useAppTheme(); const { user, signOut } = useAuth(); const { state, updatePreferences, resetData, exportSnapshot } = useHappy();
  const personalMoments = useMemo(() => state.moments.filter((moment) => moment.authorId === state.currentMemberId), [state.moments, state.currentMemberId]);
  const favorite = personalMoments.find((moment) => moment.isFavorite); const appearanceOptions: AppearancePreference[] = ["system", "light", "dark"];
  async function toggleReminder(enabled: boolean) {
    try { const result = await updateDailyReminder(enabled); if (result === "denied") { Alert.alert("Notifications are off", "You can allow HappyMe reminders later in iOS Settings."); haptic.error(); return; } if (result === "unavailable") Alert.alert("Try this on your phone", "Local reminders are available in the native iOS and Android app."); await updatePreferences({ remindersEnabled: enabled }); haptic.medium(); }
    catch { Alert.alert("Reminder not scheduled", "Your preference was not changed. Please try again on your device."); haptic.error(); }
  }
  async function exportData() { try { await Share.share({ title: "HappyMe backup", message: exportSnapshot() }); } catch { Alert.alert("Could not open sharing", "Your local data was not changed."); } }
  function confirmReset() { Alert.alert("Delete all your moments?", "This permanently removes your moments from HappyMe on every signed-in device. Your account, pods, and kindness messages will remain.", [{ text: "Cancel", style: "cancel" }, { text: "Delete all", style: "destructive", onPress: () => { void resetData().then(() => haptic.medium()).catch(() => Alert.alert("Moments not deleted", "Please check your connection and try again.")); } }]); }

  const content = <View style={styles.content}><AppHeader eyebrow="Your private space" title="You" subtitle="Preferences, privacy, and the joy you have kept." />
    <View style={[styles.profileCard, { backgroundColor: colors.ink }]}><View style={[styles.bigAvatar, { backgroundColor: colors.primary }]}><Text style={[styles.bigInitials, { color: colors.ink }]}>{state.preferences.displayName.slice(0, 2).toUpperCase()}</Text></View><View style={styles.profileCopy}><Text style={styles.profileName}>{state.preferences.displayName}</Text><Text style={styles.profilePromise} numberOfLines={1}>{user?.email ?? "Private HappyMe account"}</Text></View><AppIcon name="shield-checkmark" size={25} color={colors.mint} /></View>
    <View style={styles.stats}><View style={[styles.stat, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text style={[styles.statNumber, { color: colors.ink }]}>{personalMoments.length}</Text><Text style={[styles.statLabel, { color: colors.muted }]}>moments</Text></View><View style={[styles.stat, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text style={[styles.statNumber, { color: colors.ink }]}>{uniqueDayCount(personalMoments.map((moment) => moment.createdAt))}</Text><Text style={[styles.statLabel, { color: colors.muted }]}>days noticed</Text></View><View style={[styles.stat, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text style={[styles.statNumber, { color: colors.ink }]}>{personalMoments.filter((moment) => moment.isFavorite).length}</Text><Text style={[styles.statLabel, { color: colors.muted }]}>favorites</Text></View></View>
    {favorite ? <Pressable onPress={() => router.push({ pathname: "/moment/[id]", params: { id: favorite.id } } as never)} style={({ pressed }) => [styles.favorite, { backgroundColor: colors.primarySoft, opacity: pressed ? 0.7 : 1 }]}><AppIcon name="bookmark" size={20} color={colors.coral} /><View style={styles.favoriteCopy}><Text style={[styles.favoriteLabel, { color: colors.muted }]}>A FAVORITE MEMORY</Text><Text numberOfLines={2} style={[styles.favoriteText, { color: colors.ink }]}>{favorite.text}</Text></View><AppIcon name="chevron-forward" size={18} color={colors.muted} /></Pressable> : null}
    <View><Text style={[styles.groupLabel, { color: colors.muted }]}>APPEARANCE</Text><View style={[styles.group, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={styles.appearanceRow}>{appearanceOptions.map((item) => { const selected = state.preferences.appearance === item; return <Pressable key={item} onPress={() => { haptic.selection(); void updatePreferences({ appearance: item }).catch(() => haptic.error()); }} style={[styles.appearanceChoice, { backgroundColor: selected ? colors.ink : colors.surfaceAlt }]}><AppIcon name={item === "system" ? "phone-portrait-outline" : item === "light" ? "sunny-outline" : "moon-outline"} size={17} color={selected ? colors.background : colors.muted} /><Text style={[styles.appearanceText, { color: selected ? colors.background : colors.muted }]}>{item[0].toUpperCase() + item.slice(1)}</Text></Pressable>; })}</View></View></View>
    <View><Text style={[styles.groupLabel, { color: colors.muted }]}>GENTLE SUPPORT</Text><View style={[styles.group, { backgroundColor: colors.surface, borderColor: colors.border }]}><SettingsRow icon="notifications-outline" title="Evening reminder" detail="A quiet nudge at 8:30 PM"><Switch value={state.preferences.remindersEnabled} onValueChange={toggleReminder} trackColor={{ false: colors.border, true: colors.primary }} thumbColor={isDark ? colors.ink : colors.white} /></SettingsRow><View style={[styles.divider, { backgroundColor: colors.border }]} /><SettingsRow icon="sparkles-outline" title="Celebration feedback" detail="Haptics for happy saves"><Switch value={state.preferences.celebrationSounds} onValueChange={(value) => { haptic.medium(); void updatePreferences({ celebrationSounds: value }).catch(() => haptic.error()); }} trackColor={{ false: colors.border, true: colors.primary }} thumbColor={isDark ? colors.ink : colors.white} /></SettingsRow></View></View>
    <View><Text style={[styles.groupLabel, { color: colors.muted }]}>PRIVACY & DATA</Text><View style={[styles.group, { backgroundColor: colors.surface, borderColor: colors.border }]}><SettingsRow icon="download-outline" title="Export a backup" detail="Share a portable JSON copy" onPress={exportData} /><View style={[styles.divider, { backgroundColor: colors.border }]} /><SettingsRow icon="cloud-done-outline" title="Private cloud sync" detail="Available on your signed-in devices" /><View style={[styles.divider, { backgroundColor: colors.border }]} /><SettingsRow icon="trash-bin-outline" title="Delete all moments" detail="Remove your moments from every device" danger onPress={confirmReset} /></View></View>
    <View><Text style={[styles.groupLabel, { color: colors.muted }]}>PEOPLE & SAFETY</Text><View style={[styles.group, { backgroundColor: colors.surface, borderColor: colors.border }]}><SettingsRow icon="people-outline" title="Friends & requests" detail="Share your code and manage connections" onPress={() => router.push("/friends" as never)} /><View style={[styles.divider, { backgroundColor: colors.border }]} /><SettingsRow icon="shield-checkmark-outline" title="Safety & support" detail="Reports, blocking, privacy, and help" onPress={() => router.push("/support" as never)} /><View style={[styles.divider, { backgroundColor: colors.border }]} /><SettingsRow icon="document-text-outline" title="Privacy notice" detail="How HappyMe handles your information" onPress={() => router.push("/privacy" as never)} /><View style={[styles.divider, { backgroundColor: colors.border }]} /><SettingsRow icon="heart-outline" title="Terms & community standards" detail="The rules that keep HappyMe gentle" onPress={() => router.push("/terms" as never)} /></View></View>
    <View><Text style={[styles.groupLabel, { color: colors.muted }]}>ACCOUNT</Text><View style={[styles.group, { backgroundColor: colors.surface, borderColor: colors.border }]}><SettingsRow icon="log-out-outline" title="Sign out" detail="Keep your cloud account and data" onPress={() => signOut().catch(() => Alert.alert("Could not sign out", "Please check your connection and try again."))} /><View style={[styles.divider, { backgroundColor: colors.border }]} /><SettingsRow icon="trash-outline" title="Delete My Account" detail="Permanently remove your account and data" danger onPress={() => router.push("/account/delete" as never)} /></View></View>
    <View style={[styles.promise, { backgroundColor: colors.surfaceAlt }]}><AppIcon name="lock-closed" size={18} color={colors.mint} /><Text style={[styles.promiseText, { color: colors.muted }]}><Text style={{ fontWeight: "800", color: colors.ink }}>The HappyMe promise:</Text> no public follower counts, no engagement ranking, and no selling your reflection data.</Text></View>
  </View>;
  return <AppScreen><FlatList data={[]} renderItem={() => null} ListHeaderComponent={content} contentContainerStyle={styles.list} showsVerticalScrollIndicator={false} /></AppScreen>;
}

const styles = StyleSheet.create({ list: { paddingBottom: 34 }, content: { paddingHorizontal: 18, paddingTop: 12, gap: 20 }, profileCard: { minHeight: 96, borderRadius: 25, padding: 17, flexDirection: "row", alignItems: "center", gap: 13 }, bigAvatar: { width: 56, height: 56, borderRadius: 20, alignItems: "center", justifyContent: "center" }, bigInitials: { fontSize: 15, lineHeight: 20, fontWeight: "900" }, profileCopy: { flex: 1 }, profileName: { color: "#FFFFFF", fontSize: 19, lineHeight: 25, fontWeight: "800" }, profilePromise: { color: "rgba(255,255,255,0.67)", fontSize: 12, lineHeight: 17, marginTop: 2 }, stats: { flexDirection: "row", gap: 8 }, stat: { flex: 1, borderRadius: 19, borderWidth: 1, minHeight: 82, alignItems: "center", justifyContent: "center" }, statNumber: { fontSize: 23, lineHeight: 29, fontWeight: "900" }, statLabel: { fontSize: 10, lineHeight: 14, fontWeight: "700", marginTop: 1, textAlign: "center" }, favorite: { minHeight: 90, borderRadius: 22, padding: 15, flexDirection: "row", alignItems: "center", gap: 11 }, favoriteCopy: { flex: 1 }, favoriteLabel: { fontSize: 9, lineHeight: 13, letterSpacing: 1.1, fontWeight: "900" }, favoriteText: { fontSize: 14, lineHeight: 20, marginTop: 4, fontWeight: "600" }, groupLabel: { fontSize: 10, lineHeight: 14, letterSpacing: 1.2, fontWeight: "900", marginLeft: 13, marginBottom: 7 }, group: { borderRadius: 22, borderWidth: 1, padding: 6 }, row: { minHeight: 62, paddingHorizontal: 10, paddingVertical: 8, flexDirection: "row", alignItems: "center", gap: 11 }, rowIcon: { width: 38, height: 38, borderRadius: 13, alignItems: "center", justifyContent: "center" }, rowCopy: { flex: 1 }, rowTitle: { fontSize: 14, lineHeight: 19, fontWeight: "800" }, rowDetail: { fontSize: 11, lineHeight: 16, marginTop: 1 }, divider: { height: StyleSheet.hairlineWidth, marginLeft: 59 }, appearanceRow: { flexDirection: "row", gap: 6, padding: 3 }, appearanceChoice: { flex: 1, minHeight: 43, borderRadius: 15, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 5 }, appearanceText: { fontSize: 11, lineHeight: 15, fontWeight: "800" }, promise: { borderRadius: 20, padding: 15, flexDirection: "row", alignItems: "flex-start", gap: 10 }, promiseText: { flex: 1, fontSize: 12, lineHeight: 18 } });
